### PR TITLE
Ensuring templates are followed in the jobs category

### LINKED ISSUE #36: Delete any message in job channels that doesn't follow the template and send them a DM to use a proper format

### PR DESCRIPTION
**Pull request by MetalBreaker**
Fixes #36.

### CODE REVIEW

**Comment by CodeMyst** [comment]
You should remove the template command (which checks previous posts) as all previous posts already follow the template.

How extensively did you test it, make sure that it isn't *too* strict and doesn't come up with false positives. Make sure to ignore case sensitivity, links, weird spacing...

The `massivecodeblock-ignore` setting should be renamed to `job-channel-ids` or something similar so it doesn't cause confusion.

What is this horrendous code?
```cs

if (!_jobRegex.IsMatch(s.Content))
            {
                try
                {
                    (s.Author as IGuildUser).EnsureStaff();
                    await Task.Delay(500);
                }
                catch
                {
                    if (!s.Author.IsBot)
                        await s.Author.SendMessageAsync($"Hi, {s.Author.Username}. I've removed the message you've sent in #{s.Channel.Name} at {s.Timestamp.DateTime.ToString()} UTC, because you didn't follow the template. Please re-post it using the provided template that is pinned to that channel.");
                    await s.DeleteAsync();
                    await Task.Delay(1000);
                }
            }
```

Especially the try catch part. You can just use `HasRole ("Staff")` which returns a bool.
And what's with the `Task.Delay`s?

**Comment by MetalBreaker** [comment]
That's fine. I just don't understand the "The massivecodeblock-ignore setting should be renamed to job-channel-ids or something similar so it doesn't cause confusion." comment. It would be redundant. The massivecodeblock-ignore setting has the job channels in it. It's how it was named; I didn't name it like that.

**Comment by CodeMyst** [comment]
I know, so I suggested you rename it completely since now it has 2 uses.

**Comment by MetalBreaker** [comment]
Done.

**Pull request merged**
