### PR TITLE
Update Discord.NET

### LINKED ISSUE #50: Investigate issues with code that handles the job templates
Self-explanatory.

I'm investigating.

### PR DESCRIPTION
**Pull request by MetalBreaker**
Closes #50 . Looks like it was an issue with Discord.NET that got fixed in a nightly build.

There have been a few little changes you might have noticed;
- You can't pass an EmbedBuilder to ReplyAsync anymore, use EmbedBuilder.Build()
- AddModulesAsync now needs a service provider as an argument
- A few changes to IMessage.GetReactionUsersAsync

### CODE REVIEW

**Comment by MetalBreaker** [comment]
When this gets merged, please, before deploying for the first time run "dotnet add package Discord.Net -v 2.0.0-beta2-00982 -s https://www.myget.org/F/rogueexception/api/v3/index.json" once to register MyGet as a NuGet package source or else dotnet run/build/publish won't know from where to get Discord.NET and will error out.

**Comment by Duxez** [comment]
NEVER UPDATE TO A BETA VERSION WHEN IT'S USED FOR A PUBLISHED SYSTEM

**Comment by MetalBreaker** [comment]
Well, if something breaks we could always just revert. Anyhow, it was necessary because of a bug that screwed up the template enforcement that was patched in a beta.

**Comment by MetalBreaker** [comment]
Just because it's a beta doesn't mean it's unstable.
As I said, we could revert.
The whole point of nightlies and betas is to download them if something's bugging you... Do you really expect Discord.NET from **September 2017** to work flawlessly with Discord right now? I don't think so.

**Comment by Duxez** [comment]
Alright so you need to get out of that mindset cause you will never find a job with people that will allow beta's to run in production.

Does beta mean it's unstable? No
Is it worth the risk in a production environment? No
A production environment should be reliable and sadly beta's are not. You can't rely on the stability of a bit cause then it wouldn't be a beta.

**Comment by MetalBreaker** [comment]
Yeah. I understand and I see where you're coming from, but just... please. Trust me on this one. This one time. If something breaks, you can put all the blame on me and I will revert the project to a stable version from September 2017.

**Comment by Duxez** [comment]
I'm not expecting anything to break. I'm not going to put the blame on you cause I could have simply not pulled the latest version of the bot.

I'm simply trying to make you understand you should never have beta versions on a production environment

**Comment by MetalBreaker** [comment]
Yes. I understand.

**Comment by CodeMyst** [comment]
I agree with @Duxez but this isn't a really big problem if we run a beta in production. This is a pretty small bot.

We'll leave it be until further discussion. I don't think it's a big problem if it only affects the job channels. Closing for now. If you want to continue the discussion open another issue instead of having a conversation in a merged PR.

**Pull request merged**
